version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: maailmanilmaa
      MARIADB_DATABASE: tatskatytot
      MARIADB_USER: appuser
      MARIADB_PASSWORD: maailmanilmaa
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  javafx-app:
    build: .
    container_name: javafx-app
    depends_on:
      - mariadb
    environment:
      - DISPLAY=host.docker.internal:0.0
      - DB_HOST=mariadb
      - DB_NAME=tatskatytot
      - DB_USER=appuser
      - DB_PASSWORD=maailmanilmaa
    stdin_open: true
    tty: true

volumes:
  mariadb_data:
